In [1]:
import numpy as np

In [30]:
a = np.random.randint(10, 100, (3, 5))
a

array([[87, 19, 88, 39, 26],
       [92, 39, 12, 82, 53],
       [23, 69, 76, 34, 84]])

In [7]:
# np.zeros((3, 5), order = 'C')

In [8]:
a

array([[69, 32, 87, 13, 88],
       [43, 46, 22, 94, 31],
       [39, 80, 65, 52, 17]])

### Accessing Values from an Array - Indexing and Slicing

In [25]:
a

array([[69, 32, 87, 13, 88],
       [43, 46, 22, 94, 31],
       [39, 80, 65, 52, 17]])

In [10]:
a[:, :] #Accesses all the values

array([[69, 32, 87, 13, 88],
       [43, 46, 22, 94, 31],
       [39, 80, 65, 52, 17]])

In [26]:
a.shape

(3, 5)

In [11]:
a[0] #First Row

array([69, 32, 87, 13, 88])

In [12]:
a[2] #Third row

array([39, 80, 65, 52, 17])

In [13]:
a[:, 2] # All the rows from Third Column

array([87, 22, 65])

In [14]:
a

array([[69, 32, 87, 13, 88],
       [43, 46, 22, 94, 31],
       [39, 80, 65, 52, 17]])

In [15]:
a[1:, :] # From Second Row

array([[43, 46, 22, 94, 31],
       [39, 80, 65, 52, 17]])

In [16]:
a[:2, :] #Until 2nd Row

array([[69, 32, 87, 13, 88],
       [43, 46, 22, 94, 31]])

In [17]:
a[:, 2:]

array([[87, 13, 88],
       [22, 94, 31],
       [65, 52, 17]])

In [18]:
a[:, :2]

array([[69, 32],
       [43, 46],
       [39, 80]])

In [19]:
a

array([[69, 32, 87, 13, 88],
       [43, 46, 22, 94, 31],
       [39, 80, 65, 52, 17]])

In [20]:
a[1:, 2:4]

array([[22, 94],
       [65, 52]])

In [21]:
a[[0, 2], :] # First and Third Row

array([[69, 32, 87, 13, 88],
       [39, 80, 65, 52, 17]])

In [22]:
a[:, [1, 3]] # First and Third Columns

array([[32, 13],
       [46, 94],
       [80, 52]])

In [23]:
a

array([[69, 32, 87, 13, 88],
       [43, 46, 22, 94, 31],
       [39, 80, 65, 52, 17]])

In [24]:
a[1, 1]

46

# Boolean Indexing
## Boolean Indexing
### Boolean Indexing

* First Point
* Second Point

In [27]:
a

array([[69, 32, 87, 13, 88],
       [43, 46, 22, 94, 31],
       [39, 80, 65, 52, 17]])

In [28]:
a = list(range(10))
a

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [29]:
a % 4 == 0

TypeError: unsupported operand type(s) for %: 'list' and 'int'

In [31]:
a

array([[87, 19, 88, 39, 26],
       [92, 39, 12, 82, 53],
       [23, 69, 76, 34, 84]])

In [32]:
a % 6 == 0

array([[False, False, False, False, False],
       [False, False,  True, False, False],
       [False, False, False, False,  True]])

In [33]:
a[a % 6 == 0]

array([12, 84])

In [35]:
a[a % 4 == 0]

array([88, 92, 12, 76, 84])

In [36]:
a

array([[87, 19, 88, 39, 26],
       [92, 39, 12, 82, 53],
       [23, 69, 76, 34, 84]])

# Operations in Arrays

In [37]:
a

array([[87, 19, 88, 39, 26],
       [92, 39, 12, 82, 53],
       [23, 69, 76, 34, 84]])

# Arithmetic and Elementwise, Aggregation, Axis-wise Operations and Stacking

In [38]:
l = list(range(10))
l

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [39]:
l + 10

TypeError: can only concatenate list (not "int") to list

In [40]:
[i+10 for i in l]

[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [41]:
a

array([[87, 19, 88, 39, 26],
       [92, 39, 12, 82, 53],
       [23, 69, 76, 34, 84]])

In [42]:
a + 10

array([[ 97,  29,  98,  49,  36],
       [102,  49,  22,  92,  63],
       [ 33,  79,  86,  44,  94]])

In [44]:
a - 10

array([[77,  9, 78, 29, 16],
       [82, 29,  2, 72, 43],
       [13, 59, 66, 24, 74]])

In [45]:
a * 2

array([[174,  38, 176,  78,  52],
       [184,  78,  24, 164, 106],
       [ 46, 138, 152,  68, 168]])

In [46]:
a / 2

array([[43.5,  9.5, 44. , 19.5, 13. ],
       [46. , 19.5,  6. , 41. , 26.5],
       [11.5, 34.5, 38. , 17. , 42. ]])

In [47]:
a // 2

array([[43,  9, 44, 19, 13],
       [46, 19,  6, 41, 26],
       [11, 34, 38, 17, 42]], dtype=int32)

In [49]:
a % 6

array([[3, 1, 4, 3, 2],
       [2, 3, 0, 4, 5],
       [5, 3, 4, 4, 0]], dtype=int32)

In [61]:
a

array([[87, 19, 88, 39, 26],
       [92, 39, 12, 82, 53],
       [23, 69, 76, 34, 84]])

In [50]:
a ** 2

array([[7569,  361, 7744, 1521,  676],
       [8464, 1521,  144, 6724, 2809],
       [ 529, 4761, 5776, 1156, 7056]], dtype=int32)

In [51]:
a

array([[87, 19, 88, 39, 26],
       [92, 39, 12, 82, 53],
       [23, 69, 76, 34, 84]])

In [52]:
np.add(a, 10)

array([[ 97,  29,  98,  49,  36],
       [102,  49,  22,  92,  63],
       [ 33,  79,  86,  44,  94]])

In [53]:
np.subtract(a, 10)

array([[77,  9, 78, 29, 16],
       [82, 29,  2, 72, 43],
       [13, 59, 66, 24, 74]])

In [56]:
np.multiply(a, 2)

array([[174,  38, 176,  78,  52],
       [184,  78,  24, 164, 106],
       [ 46, 138, 152,  68, 168]])

In [57]:
np.sqrt(a)

array([[9.32737905, 4.35889894, 9.38083152, 6.244998  , 5.09901951],
       [9.59166305, 6.244998  , 3.46410162, 9.05538514, 7.28010989],
       [4.79583152, 8.30662386, 8.71779789, 5.83095189, 9.16515139]])

In [59]:
b = 10
b ** 3

1000

In [60]:
b = 43
b % 6

1

# Aggregation Operations

In [63]:
a

array([[87, 19, 88, 39, 26],
       [92, 39, 12, 82, 53],
       [23, 69, 76, 34, 84]])

In [64]:
a.sum()

823

In [65]:
a.min()

12

In [66]:
a.max()

92

In [67]:
a.mean()

54.86666666666667

In [68]:
a.std()

27.875596655298498

In [69]:
a.var()

777.0488888888888

In [72]:
a

array([[87, 19, 88, 39, 26],
       [92, 39, 12, 82, 53],
       [23, 69, 76, 34, 84]])

In [73]:
a[a % 2 == 1]

array([87, 19, 39, 39, 53, 23, 69])

In [74]:
a[a % 2 == 1].sum()

329

In [70]:
a[a % 2 == 0]

array([88, 26, 92, 12, 82, 76, 34, 84])

In [71]:
a[a % 2 == 0].sum()

494

In [75]:
a % 2 == 0

array([[False, False,  True, False,  True],
       [ True, False,  True,  True, False],
       [False, False,  True,  True,  True]])

In [76]:
a

array([[87, 19, 88, 39, 26],
       [92, 39, 12, 82, 53],
       [23, 69, 76, 34, 84]])

In [77]:
a.sum()

823

In [78]:
a[a % 3 == 0]

array([87, 39, 39, 12, 69, 84])

In [79]:
a[a % 3 == 0].sum()

330

In [82]:
a

array([[87, 19, 88, 39, 26],
       [92, 39, 12, 82, 53],
       [23, 69, 76, 34, 84]])

In [88]:
a.all()

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [93]:
a[(a%3 == 0) & (a%4 == 0)]

array([12, 84])

# Axis-wise Operations

In [94]:
l

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [95]:
l.sum()

AttributeError: 'list' object has no attribute 'sum'

In [96]:
l.mean()

AttributeError: 'list' object has no attribute 'mean'

In [106]:
import keyword
print(keyword.kwlist)

['False', 'None', 'True', '__peg_parser__', 'and', 'as', 'assert', 'async', 'await', 'break', 'class', 'continue', 'def', 'del', 'elif', 'else', 'except', 'finally', 'for', 'from', 'global', 'if', 'import', 'in', 'is', 'lambda', 'nonlocal', 'not', 'or', 'pass', 'raise', 'return', 'try', 'while', 'with', 'yield']


In [172]:
len(keyword.kwlist)

36

In [107]:
print("One")
print("Two")

One
Two


In [108]:
print("One", end = " ")
print("Two")

One Two


In [100]:
a

array([[87, 19, 88, 39, 26],
       [92, 39, 12, 82, 53],
       [23, 69, 76, 34, 84]])

In [101]:
a.sum()

823

In [102]:
a.sum(axis = 0) # 0 Means Cols and 1 Means Rows

array([202, 127, 176, 155, 163])

In [103]:
a.sum(axis = 1)

array([259, 278, 286])

In [104]:
a.mean(axis = 0)

array([67.33333333, 42.33333333, 58.66666667, 51.66666667, 54.33333333])

In [105]:
a.mean(axis = 1)

array([51.8, 55.6, 57.2])

In [110]:
np.around(a.mean(axis = 0), 2)

array([67.33, 42.33, 58.67, 51.67, 54.33])

# Concatenation, Stack and Split

In [111]:
a

array([[87, 19, 88, 39, 26],
       [92, 39, 12, 82, 53],
       [23, 69, 76, 34, 84]])

In [112]:
b = np.array([[1,2], [3,4]])
b

array([[1, 2],
       [3, 4]])

In [113]:
c = np.array([[5,6]])
c

array([[5, 6]])

In [131]:
c.ndim

2

In [132]:
c.shape

(1, 2)

In [127]:
d = np.array([5,6])
d

array([5, 6])

In [128]:
d.ndim

1

In [129]:
d.shape

(2,)

In [115]:
np.concatenate([b, c]) #Axis = 0 Means Row and Axis = 1 Means Columns

array([[1, 2],
       [3, 4],
       [5, 6]])

In [116]:
b.shape

(2, 2)

In [117]:
c.shape

(1, 2)

In [118]:
np.concatenate([b, c], axis = 1)

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

In [120]:
c

array([[5, 6]])

In [122]:
c.T

array([[5],
       [6]])

In [123]:
np.concatenate([b, c.T], axis = 1)

array([[1, 2, 5],
       [3, 4, 6]])

In [124]:
c

array([[5, 6]])

In [125]:
b

array([[1, 2],
       [3, 4]])

In [133]:
"Python " + "Programming"

'Python Programming'

In [134]:
b

array([[1, 2],
       [3, 4]])

In [135]:
c

array([[5, 6]])

In [136]:
np.concatenate([b, c])

array([[1, 2],
       [3, 4],
       [5, 6]])

In [139]:
np.concatenate([b, c.T], axis = 1)

array([[1, 2, 5],
       [3, 4, 6]])

In [140]:
c.T

array([[5],
       [6]])

In [141]:
c

array([[5, 6]])

In [143]:
np.vstack([b, c])

array([[1, 2],
       [3, 4],
       [5, 6]])

In [144]:
np.hstack([b, c.T])

array([[1, 2, 5],
       [3, 4, 6]])

In [145]:
a

array([[87, 19, 88, 39, 26],
       [92, 39, 12, 82, 53],
       [23, 69, 76, 34, 84]])

In [146]:
np.pi

3.141592653589793

In [147]:
a.shape

(3, 5)

In [148]:
a.size

15

In [149]:
a

array([[87, 19, 88, 39, 26],
       [92, 39, 12, 82, 53],
       [23, 69, 76, 34, 84]])

In [151]:
np.hsplit(a, 5)

[array([[87],
        [92],
        [23]]),
 array([[19],
        [39],
        [69]]),
 array([[88],
        [12],
        [76]]),
 array([[39],
        [82],
        [34]]),
 array([[26],
        [53],
        [84]])]

In [152]:
np.vsplit(a, 3)

[array([[87, 19, 88, 39, 26]]),
 array([[92, 39, 12, 82, 53]]),
 array([[23, 69, 76, 34, 84]])]

In [153]:
a

array([[87, 19, 88, 39, 26],
       [92, 39, 12, 82, 53],
       [23, 69, 76, 34, 84]])

In [154]:
a.reshape(5,3)

array([[87, 19, 88],
       [39, 26, 92],
       [39, 12, 82],
       [53, 23, 69],
       [76, 34, 84]])

In [155]:
a.reshape(15,1)

array([[87],
       [19],
       [88],
       [39],
       [26],
       [92],
       [39],
       [12],
       [82],
       [53],
       [23],
       [69],
       [76],
       [34],
       [84]])

In [156]:
a.ravel()

array([87, 19, 88, 39, 26, 92, 39, 12, 82, 53, 23, 69, 76, 34, 84])

In [165]:
np.vsplit(a, 3)

[array([[87, 19, 88, 39, 26]]),
 array([[92, 39, 12, 82, 53]]),
 array([[23, 69, 76, 34, 84]])]

In [157]:
first_row = np.vsplit(a, 3)[0]
second_row = np.vsplit(a, 3)[1]
third_row = np.vsplit(a, 3)[2]

In [159]:
second_row

array([[92, 39, 12, 82, 53]])

In [160]:
third_row

array([[23, 69, 76, 34, 84]])

In [158]:
first_row

array([[87, 19, 88, 39, 26]])

In [166]:
a = np.random.randint(10, 100, (4, 4))
a

array([[43, 84, 65, 99],
       [90, 92, 98, 48],
       [72, 48, 48, 80],
       [19, 72, 82, 36]])

In [167]:
a.reshape(8,2)

array([[43, 84],
       [65, 99],
       [90, 92],
       [98, 48],
       [72, 48],
       [48, 80],
       [19, 72],
       [82, 36]])

#### resize(), Accessing alternate arrays, Order arg

In [ ]:
np.array # Shift + Tab

In [168]:
a

array([[43, 84, 65, 99],
       [90, 92, 98, 48],
       [72, 48, 48, 80],
       [19, 72, 82, 36]])

In [169]:
a[0] = np.array([1,2,3,4])
a

array([[ 1,  2,  3,  4],
       [90, 92, 98, 48],
       [72, 48, 48, 80],
       [19, 72, 82, 36]])

In [170]:
a

array([[ 1,  2,  3,  4],
       [90, 92, 98, 48],
       [72, 48, 48, 80],
       [19, 72, 82, 36]])

In [ ]:
a[1, 3]

In [171]:
a.T

array([[ 1, 90, 72, 19],
       [ 2, 92, 48, 72],
       [ 3, 98, 48, 82],
       [ 4, 48, 80, 36]])

In [173]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [175]:
a.ndim

1

In [176]:
a = np.array([[1,2,3], [4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [177]:
a.ndim

2

In [178]:
a = np.array([[[12,13,14], [1,2,3], [4,5,6]]])
a

array([[[12, 13, 14],
        [ 1,  2,  3],
        [ 4,  5,  6]]])

In [179]:
a.ndim

3

In [180]:
a.shape

(1, 3, 3)

In [181]:
a = np.array([[[[12,13,14], [1,2,3], [4,5,6], [1,2,3]]]])
a

array([[[[12, 13, 14],
         [ 1,  2,  3],
         [ 4,  5,  6],
         [ 1,  2,  3]]]])

In [182]:
a.ndim

4

In [183]:
a.shape

(1, 1, 4, 3)